# Navigation links
main:
  - name: Consulting
    url: "consulting/"
    weight: 10
  - name: Blog
    url: 'post/' # Links to /content/post
    weight: 20 # Order of the weight determines order in navigation pane
  - name: R Packages
    url: "project/"
    weight: 30
  - name: About
    url: "about/"
    weight: 40
  - name: Contact
    url: '#contact' # Links to the widget found in /content/home
    weight: 50
  - name: Publications
    url: 'publications/'
    weight: 60
