# Site setup
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
theme: custom_site_theme # References custom color theme set in /data/themes/custom_site_theme.toml
day_night: true
font: mrrobot # Can reference custom font set in /data/fonts/custom_site_font.toml via 'custom_site_font'
font_size: S

# SEO (https://wowchemy.com/docs/hugo-tutorials/seo/)
site_type: 'LocalBusiness' # https://wowchemy.com/docs/hugo-tutorials/seo/#improve-your-search-engine-and-social-network-previews
local_business_type: 'ProfessionalService' # https://schema.org/LocalBusiness#subtypes
org_name: 'Zajichek Stats'
description: 'Data science and statistical consulting in Central Wisconsin and beyond'

# Contact (displays under the Contact widget on the homepage)
email: alexzajichek@gmail.com
contact_links:
  - icon: linkedin
    icon_pack: fab
    name: Connect with me
    link: https://www.linkedin.com/in/alexzajichek/

# Site header
main_menu:
  enable: true
  align: l
  show_logo: true
  show_language: false
  show_day_night: true
  show_search: true
  highlight_active_link: true

# Localization
date_format: 'Jan 2, 2006'
time_format: '3:04 PM'
address_format: en-us

# Site features
highlight: true
highlight_languages:
  - r
  - python
  - latex
math: true
diagram: false
privacy_pack: false
edit_page:
  repo_url: ''
  content_dir: ''
  repo_branch: main
  editable:
    page: false
    post: false
    book: false
show_related:
  book: true
  page: false
  post: true
  project: true
  publication: true
  event: true
reading_time: true
section_pager: false
docs_section_pager: true
sharing: true
copyright_license:
  enable: false
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'
abstract_length: 135
plugins_js: []
avatar:
  gravatar: false
  shape: circle
publications:
  date_format: January 2006
  citation_style: apa
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
breadcrumb:
  page_types:
    book: true
comments:
  provider: ''
  commentable:
    post: true
    book: true
    project: true
    publication: true
    event: true
  disqus:
    shortname: 'https-www-zajichekstats-com'
    show_count: true
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
map:
  provider: mapnik
  api_key: ''
  zoom: 15
marketing:
  google_analytics: 'G-9MW3W3RQD9'
  google_tag_manager: ''
  google_site_verification: '' # https://search.google.com/search-console/welcome
  baidu_site_verification: ''
  baidu_tongji: ''
cms:
  branch: master
  local_backend: false
icon:
  pack:
    ai: false
