project:
  type: website

website:
  title: "Zajichek Stats"
  favicon: "favicon.png"
  google-analytics: "G-9MW3W3RQD9"
  site-url: https://www.zajichekstats.com/
  repo-url: https://github.com/zajichek/zajichek
  description: "Statistician/data scientist in Central Wisconsin."
  page-footer: "© 2025 Zajichek Stats"
  open-graph: true
  draft-mode: unlinked
  navbar:
    logo: "logo.png"
    title: false
    left:
      - href: presentations.qmd
        text: Projects & Presentations
      - href: publications.qmd
        text: Publications
      - href: https://www.centralstatz.com/
        text: Consultancy 
      - href: about.qmd
        text: About
      - href: https://dashboard.mailerlite.com/forms/1517199/154300987644839168/share
        text: Subscribe
    right:
      - icon: envelope
        href: "mailto:alex@centralstatz.com"
      - icon: linkedin
        href: https://www.linkedin.com/in/alexzajichek
        aria-label: LinkedIn
      - icon: github
        href: https://github.com/zajichek
        aria-label: GitHub
      - icon: youtube
        href: https://www.youtube.com/@centralstatz
        aria-label: YouTube
      - icon: rss
        href: index.xml

format:
  html:
    theme: [styles.scss, default]

editor: source