{
  "hash": "8d38eebc5ec51dd305ce7f32983f2151",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"How to reconcile the regression equation from spline terms\"\ndescription: \"Using the {rms::rcs} function\"\nauthor: \"Alex Zajichek\"\ndate: \"11/25/2024\"\nimage: \"feature.png\"\ncategories:\n  - Regression\nformat:\n  html:\n    code-fold: true\n    code-tools: true\n---\n\n{{< video https://www.youtube.com/embed/HXTjssAYCdw >}}\n\n\n\n\nSuppose we want to model blood pressure as a function of age (dataset details found [here](https://archive.ics.uci.edu/dataset/45/heart+disease)):\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load packages\nlibrary(tidyverse)\n\n# Extract the data set\ndat <- cheese::heart_disease\n\n# Make a plot\ndat |>\n  ggplot() +\n  geom_point(\n    aes(\n      x = Age,\n      y = BP\n    ),\n    shape = 21,\n    size = 3,\n    fill = \"brown\",\n    alpha = .5\n  ) +\n  xlab(\"Age (years)\") +\n  ylab(\"Systolic blood pressure\") +\n  theme(\n    panel.background = element_blank(),\n    axis.title = element_text(size = 16),\n    axis.text = element_text(size = 12)\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\n\nIt looks like a larger age is associated with a larger blood pressure, on average, so we fit a [simple linear regression](https://en.wikipedia.org/wiki/Simple_linear_regression) model:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit the model\nmod1 <- lm(BP ~ Age, data = dat)\nsummary(mod1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = BP ~ Age, data = dat)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-38.659 -11.449  -0.904  10.218  67.444 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 101.4851     5.9364  17.095  < 2e-16 ***\nAge           0.5548     0.1076   5.157 4.55e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 16.9 on 301 degrees of freedom\nMultiple R-squared:  0.08119,\tAdjusted R-squared:  0.07814 \nF-statistic:  26.6 on 1 and 301 DF,  p-value: 4.547e-07\n```\n\n\n:::\n:::\n\n\n\nWe estimate that for every 10 year increase in age, systolic blood pressure increases by 5.5 mmHg. We can also write out the full regression equation for estimating the blood pressure given a new patient's age:\n\n$$BP = 101.49 + 0.56 \\times Age$$\n\nAnd we can add this to our plot to get a visual.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Make a plot\ndat |>\n  ggplot() +\n  geom_point(\n    aes(\n      x = Age,\n      y = BP\n    ),\n    shape = 21,\n    size = 3,\n    fill = \"brown\",\n    alpha = .5\n  ) +\n  geom_abline(\n    slope = mod1$coefficients[[2]],\n    intercept = mod1$coefficients[[1]],\n    linewidth = 2\n  ) +\n  xlab(\"Age (years)\") +\n  ylab(\"Systolic blood pressure\") +\n  theme(\n    panel.background = element_blank(),\n    axis.title = element_text(size = 16),\n    axis.text = element_text(size = 12)\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n\nSimple enough. We can verify our formula works by comparing with the output of the `predict` function:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(\n  BP1 = predict(mod1, newdata = dat),\n  BP2 = mod1$coefficients[[1]] + mod1$coefficients[[2]] * dat$Age\n) |>\n  with(data = _, paste0(round(100 * mean(near(BP1, BP2))), \"% of fitted values match.\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"100% of fitted values match.\"\n```\n\n\n:::\n:::\n\n\n\nAs we can see, all of the predictions match, thus we understand exactly how the model works.\n\n### Adding spline terms\n\nNow suppose from the plot above we argue there may be a nonlinear relationship between age and blood pressure, such that it only slightly increases at lower ages and then accelerates in higher ages. So we choose to use a [restricted cubic spline](https://en.wikipedia.org/wiki/Spline_(mathematics)) with 3 knots:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod2 <- lm(BP ~ rms::rcs(Age, 3), data = dat)\nsummary(mod2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = BP ~ rms::rcs(Age, 3), data = dat)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-37.817 -11.576  -1.212   9.642  66.782 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)           94.8089    11.2104   8.457 1.22e-15 ***\nrms::rcs(Age, 3)Age    0.7016     0.2351   2.984  0.00308 ** \nrms::rcs(Age, 3)Age'  -0.1854     0.2640  -0.702  0.48305    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 16.91 on 300 degrees of freedom\nMultiple R-squared:  0.0827,\tAdjusted R-squared:  0.07659 \nF-statistic: 13.52 on 2 and 300 DF,  p-value: 2.38e-06\n```\n\n\n:::\n:::\n\n\n\nWe can see there are now 2 parameters in the model to capture the age effect. We can again plot this to see what it looks like:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Make a plot\ndat |>\n  ggplot() +\n  geom_point(\n    aes(\n      x = Age,\n      y = BP\n    ),\n    shape = 21,\n    size = 3,\n    fill = \"brown\",\n    alpha = .5\n  ) +\n  geom_line(\n    data = tibble(Age = unique(dat$Age), Fitted = predict(mod2, newdata = tibble(Age = unique(dat$Age)))),\n    aes(\n      x = Age,\n      y = Fitted\n    ),\n    linewidth = 2\n  ) +\n  xlab(\"Age (years)\") +\n  ylab(\"Systolic blood pressure\") +\n  theme(\n    panel.background = element_blank(),\n    axis.title = element_text(size = 16),\n    axis.text = element_text(size = 12)\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\nThe estimated curve didn't take the shape of what we suspected (and maybe with more flexibility (i.e., knots), it would), but we'll run with it anyway. \n\n### Writing the regression equation\n\nThe question is: _how do we write out the formula for this model such that we input an age (in years) and get a predicted blood pressure?_\n\nIf we did what we did before with [simple linear regression](https://en.wikipedia.org/wiki/Simple_linear_regression) and just blindly plug in age to what is given from the model output above, we'd have:\n\n$$BP = 94.8 + 0.70 \\times Age - 0.19 \\times Age $$\n\nNow if we again compare the output of that equation with what the correct fitted values are from the `predict` function:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Gather set of predicted values\npreds <-\n  tibble(\n    BP1 = predict(mod2, newdata = dat),\n    BP2 = mod2$coefficients[[1]] + mod2$coefficients[[2]] * dat$Age + mod2$coefficients[[3]] * dat$Age\n  )\n\n# Check concordance\nwith(data = preds, paste0(round(100 * mean(near(BP1, BP2))), \"% of fitted values match.\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"0% of fitted values match.\"\n```\n\n\n:::\n:::\n\n\n\nIt turns out _none_ of them are correct. So obviously something is wrong.\n\n### Find the knot locations\n\nFirst, we need to figure out what gets inputted into the equation. The coefficient for the second age term in the model output (-0.185) is not multiplied by the raw age value, but rather by some transformation of it.\n\nSpecifically, we can [recall](https://www.zajichekstats.com/post/the-evasive-spline/) that age on the original scale will be transformed by a truncated power basis _at each knot_:\n\n$$h(x,\\nu) = (x-\\nu)^3_+$$\n\nwhere $\\nu$ is the knot location and $+$ means we take $(x-\\nu)^3$ if $x>\\nu$ and 0 otherwise.\n\nIn our example, we have 3 knot locations:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract knot locations\nknots <- attr(rms::rcs(dat$Age, 3), \"parms\")\nknots\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 42 56 66\n```\n\n\n:::\n:::\n\n\n\nWe can verify that these are the $10^{th}$, $50^{th}$ and $90^{th}$ percentiles of the age distribution (which is the default).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquantile(dat$Age, c(.1, .5, .9))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n10% 50% 90% \n 42  56  66 \n```\n\n\n:::\n:::\n\n\n\nThen, we can write out the full transformation for the spline term using the [formula](https://support.sas.com/resources/papers/proceedings16/5621-2016.pdf):\n\n$$X_{trans} = (x-\\nu_1)^3_+ - \\frac{\\nu_3 - \\nu_1}{\\nu_3 - \\nu_2}(x-\\nu_2)^3_+ + \\frac{\\nu_2 - \\nu_1}{\\nu_3 - \\nu_2}(x-\\nu_3)^3_+$$\n\nPlugging in our quantities, we get:\n\n$$Age_{spline} = (age - 42)^3_+ - \\frac{66-42}{66-56}(age - 56)^3_+ + \\frac{56-42}{66-56}(age - 66)^3_+$$\n\nAhhh okay. So we need to take our raw age value, first plug it into that formula, and _then_ multiply it by the coefficient from the model's output. In sloppy notation, something like this:\n\n$$BP = 94.8 + 0.70 \\times Age - 0.19 \\times Age_{spline}$$\n\nSo we'll do that, again comparing with the correct output of the `predict` function:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compute the spline value\nage_spline <- \n  pmax((dat$Age-knots[1]), 0)^3 - \n  (knots[3] - knots[1])/(knots[3] - knots[2]) * pmax((dat$Age-knots[2]), 0)^3 + \n  (knots[2] - knots[1])/(knots[3] - knots[2]) * pmax((dat$Age-knots[3]), 0)^3\n\n# Add new calculation\npreds$BP3 <- mod2$coefficients[[1]] + mod2$coefficients[[2]] * dat$Age + mod2$coefficients[[3]] * age_spline\n\n# Check concordance\nwith(data = preds, paste0(round(100 * mean(near(BP1, BP3))), \"% of fitted values match.\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"12% of fitted values match.\"\n```\n\n\n:::\n:::\n\n\n\nWe're still having problems. It looks like _some_ of the predictions from our new formula match the correct output, but most don't.\n\n### Normalizing the transformation\n\nIn the [`rms::rcs` documentation](https://www.rdocumentation.org/packages/Hmisc/versions/5.1-3/topics/rcspline.eval), it states that the default behavior (seen by the `norm` argument) is to _\"normalize by the square of the spacing between the first and last knots\"_. Applying this to our age transformation, our normalization factor is:\n\n$$Norm = (\\nu_3 - \\nu_1)^2 = (66 - 42)^2 = 24^2 = 576$$\n\nSo in finding the basis vectors for the spline term, this value was implicitly multiplied through, causing our apparent equation above to be miscalibrated from the original age scale. To remedy this, we simply need to _divide_ the model coefficient for the spline term (-0.185) by the normalization factor. So our equation becomes:\n\n$$BP = 94.8 + 0.70 \\times Age - \\frac{0.19}{Norm} \\times Age_{spline}$$\n\nWe can again check to see how this compares to the (correct) output of the `predict` function:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compute the normalizing factor\nnorm_factor <- (knots[3] - knots[1])^2\n\n# Add new calculation\npreds$BP4 <- mod2$coefficients[[1]] + mod2$coefficients[[2]] * dat$Age + mod2$coefficients[[3]] / norm_factor * age_spline \n\n# Check concordance\nwith(data = preds, paste0(round(100 * mean(near(BP1, BP4))), \"% of fitted values match.\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"100% of fitted values match.\"\n```\n\n\n:::\n:::\n\n\n\nFinally, all of our calculated predicted values are correct!\n\n### The final formula\n\nWe already wrote this out above, if you want to piece together the various components, but we'll do it again here in one fell swoop. \n\n$$\n\\begin{equation} \n\\begin{split}\nBP & = 94.8 + 0.70 \\times Age + \\\\\n & = \\frac{-0.19}{(66-42)^2} \\times \\bigg ( \\\\\n & = (Age - 42)^3_+ - \\\\\n & = \\frac{66-42}{66-56}(Age - 56)^3_+ + \\\\\n & = \\frac{56-42}{66-56}(Age - 66)^3_+ \\bigg ) \\\\\n\\end{split}\n\\end{equation}\n$$\n\nNow we have an equation that takes an age value as input (in years) and outputs the predicted systolic blood pressure. Finally, we understand exactly how _this_ model works.\n\n## Why is this useful?\n\nFirst, it's obviously important to understand how modeling software is getting to the results it gives you, so that you can correctly interpret it, among other things. Second, from a pragmatic point of view, the ability to write out the full regression equation allows you embed your model into any application (even Excel if you wanted), instead of requiring the `predict` function to be run, which in turn would require `R` to be a part of the application's server. In this case, it's unnecessary for that to be a requirement, since we can simply reconcile our model into an easily understandable equation. Luckily, there are also [some functions](https://www.rdocumentation.org/packages/rms/versions/6.8-2/topics/Function) that can extract these formulas for you for this exact purpose so you don't _have_ to go through the cumbersome calculations above.\n\n\n\n{{< bluesky-comments uri=\"at://did:plc:sh3av73hihgu72vx7k44kgv7/app.bsky.feed.post/3lbubbyx3v42m\" >}}\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}